FROM php:7.1-fpm

RUN apt-get update && apt-get -y install libicu-dev libmcrypt-dev libpng-dev openssl zlib1g-dev
RUN docker-php-ext-install gd intl mcrypt pdo pdo_mysql zip

RUN echo "memory_limit=-1" > "$PHP_INI_DIR/conf.d/memory-limit.ini" \
 && echo "date.timezone=${PHP_TIMEZONE:-UTC}" > "$PHP_INI_DIR/conf.d/date_timezone.ini"
