version: "3.2"
volumes:
  app:
  bin:
  vendor:
services:
  base: &base
    build:
      context: .
    working_dir: /opt/src
    environment:
      - SYMFONY_CACHE_DIR=/opt/app/cache
      - SYMFONY_LOG_DIR=/opt/app/log
    volumes:
      - ./app:/opt/src/app
      - ./src:/opt/src/src
      - ./web:/opt/src/web
      - ./behat.yml.dist:/opt/src/behat.yml.dist
      - ./composer.json:/opt/src/composer.json
      - ./composer.lock:/opt/src/composer.lock
      - ./dev.json:/opt/src/dev.json
      - ./dev.lock:/opt/src/dev.lock
      - app:/opt/app
      - bin:/opt/src/bin
      - vendor:/opt/src/vendor
  composer:
    <<: *base
    entrypoint:
      - /usr/local/bin/composer
  dev:
    <<: *base
    entrypoint:
      - /opt/src/app/console
    ports:
      - "8080:8080"
    command:
      - "server:run"
      - "0.0.0.0:8080"
    networks:
      - php
      - default
    depends_on:
      - message_consumer
      - db
  console: &console
    <<: *base
    entrypoint:
      - /opt/src/app/console
    networks:
      - php
    depends_on:
      - db
    stdin_open: true
    tty: true
  setup:
    <<: *console
    command: oro:install --timeout 3600 --drop-database --env=dev --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="admin1111" --user-email="admin@example.com" --organization-name="Event Genius" --application-url="http://localhost"
  message_consumer:
    <<: *base
    entrypoint:
      - /opt/src/app/console
    command: oro:message-queue:consume
    networks:
      - php
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php
      - default
    depends_on:
      - php
  php:
    <<: *base
    networks:
      - php
    depends_on:
      - message_consumer
      - db
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orocrm
      - MYSQL_USER=orocrm
      - MYSQL_PASSWORD=orocrm
    networks:
      - php
networks:
  php:
    driver: bridge
