version: "3"
services:
  composer:
    build:
      context: .
      dockerfile: Dockerfile.composer
    working_dir: /opt/src
    volumes:
      - ./:/opt/src
  setup:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - ./:/opt/src
    working_dir: /opt/src
    entrypoint:
      - /opt/src/app/console
    command: oro:install --timeout 3600 --drop-database --env=prod --user-name=admin --user-firstname=John --user-lastname=Doe --user-password="admin1111" --user-email="johndoe@example.com" --organization-name="Acme" --application-url="http://oro.loc/"
    networks:
      - php
    depends_on:
      - db
    stdin_open: true
    tty: true
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./:/opt/src
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php
      - default
    depends_on:
      - php
    environment:
      - CMD_INIT_BEFORE=
      - CMD_INIT_CLEAN=
      - CMD_INIT_INSTALLED=
      - CMD_INIT_AFTER=
      - APP_DB_DRIVER=pdo_mysql
      - APP_DB_HOST=db
      - APP_DB_PORT=3306
      - APP_DB_USER=orocrm
      - APP_DB_PASSWORD=orocrm
      - APP_DB_NAME=orocrm
      - APP_HOSTNAME=localhost
      - APP_MAILER_TRANSPORT=smtp
      - APP_MAILER_HOST=mail
      - APP_MAILER_PORT=25
      - APP_MAILER_ENCRYPTION=
      - APP_MAILER_USER=user
      - APP_MAILER_PASSWORD=password
      - APP_WEBSOCKET_BACKEND_PORT=8080  
      - APP_WEBSOCKET_FRONTEND_PORT=3088  
      - APP_SECRET=123456789    
      - APP_IS_INSTALLED=
  php:
    build:
      context: .
      dockerfile: Dockerfile.fpm
    volumes:
      - ./:/opt/src
    networks:
      - php
    depends_on:
      - db
    environment:
      - CMD_INIT_BEFORE=
      - CMD_INIT_CLEAN=
      - CMD_INIT_INSTALLED=
      - CMD_INIT_AFTER=
      - APP_DB_DRIVER=pdo_mysql
      - APP_DB_HOST=db
      - APP_DB_PORT=3306
      - APP_DB_USER=orocrm
      - APP_DB_PASSWORD=orocrm
      - APP_DB_NAME=orocrm
      - APP_HOSTNAME=localhost
      - APP_MAILER_TRANSPORT=smtp
      - APP_MAILER_HOST=mail
      - APP_MAILER_PORT=25
      - APP_MAILER_ENCRYPTION=
      - APP_MAILER_USER=user
      - APP_MAILER_PASSWORD=password
      - APP_WEBSOCKET_BACKEND_PORT=8080  
      - APP_WEBSOCKET_FRONTEND_PORT=3088  
      - APP_SECRET=123456789    
      - APP_IS_INSTALLED=
  db:
    image: mysql:5.5
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=orocrm
      - MYSQL_USER=orocrm
      - MYSQL_PASSWORD=orocrm
    networks:
      - php
networks:
  php:
    driver: bridge
